### ISSUE TITLE
Pyinstaller desktop project

### ISSUE THREAD

**Issue by csorodrigo** [botcity-dev/botcity-framework-core-python#40]
Hello, 

One question, i am trying to build a .exe with pyinstaller of the complete desktop automation, but i am having some problems when i execute, i think after the file.exe its complete, it doesnt find the images inside the resources folder.
Is there anyway i can work around this? 

Best regards

**Comment by hhslepicka** [comment]
Transferring the issue to a more appropriate repository.

**Comment by csorodrigo** [comment]
It worked! Thank you

**Comment by csorodrigo** [comment]
Hello! How are you? I tried to add the google sheet plugin and it worked just fine, but i am having some trouple adding it up on  the .exe file.  Do i have to put some extra parameter on the pyinstaller command to add the google sheet plugin? Best regards
