### ISSUE TITLE
Problem running Desktop bot on Linux OS

### ISSUE THREAD

**Issue by bugelseif** [botcity-dev/botcity-framework-core-python#44]
**Describe the bug**
When executing the command `python3 bot.py` an error occurs in the `PIL` library, returning the following error:

`ImportError: ImageGrab is macOS and Windows only`

![error_message](https://github.com/botcity-dev/botcity-framework-core-python/assets/51390917/2d24debf-f32e-439f-8d87-c15b200a97fb)

_The steps described in the documentation for possible problems in the Linux system were performed._

**Expected behavior**
The bot should run and open the system's default browser.

**Steps to Reproduce**

1. BotCity template download for desktop
2. Install dependencies
3. Run the command `python3 bot.py`

**Possible Solution**
Researching the problem, I found a lib that replaces ImageGrab for Linux systems.

Suggestion: https://stackoverflow.com/questions/43520757/imagegrab-alternative-in-linux
Package: https://pypi.org/project/pyscreenshot/

**My Platform**

* OS Version: Ubuntu 20.04.6
* Python Version: 3.8.10
* Packages Version:
![image](https://github.com/botcity-dev/botcity-framework-core-python/assets/51390917/643759c4-b214-4b4c-925f-7336dbf80977)
![image](https://github.com/botcity-dev/botcity-framework-core-python/assets/51390917/820e06d7-47ab-4285-bd0d-bc165102706c)

**Additional context**

**Comment by bugelseif** [comment]
**Additional context**
Setting `botcity-framework-core` to version `0.4.0`, the bot runs normally.

**Comment by hhslepicka** [comment]
I believe Linux support for ImageGrab was added after Pillow 7.1.0.
If it works, we can change the requirements.txt to request a version greater or equal 7.1.0
